### ISSUE TITLE
Order of attributes

### ISSUE THREAD

**Issue by romefi** [opengisch/QgisModelBaker#466]
Is there a specific reason, why the order of the attributes in the form is alphabetic and not in the order of the database-table?

![image](https://user-images.githubusercontent.com/26796989/106277915-1da65f80-623a-11eb-97c8-2c13c430c053.png)

**Comment by m-kuhn** [comment]
Not on purpose.
Should we interpret this as a feature request?

**Comment by romefi** [comment]
It would make sense in my point of view as the order of the attributes in ili-models are mostly reasonable. An interpretation as feature request would be marvelous.

**Comment by signedav** [comment]
@romefi I cannot reproduce. Maybe we fixed that once. Can you check?

**Comment by romefi** [comment]
Tested with KbS_V1_5, problem still occurs. The attributes in the formular are still ordered alphabetical and not like in table.

![image](https://user-images.githubusercontent.com/26796989/165711932-03a375ed-3c67-4574-9142-43369d602769.png)

**Comment by signedav** [comment]
Weird. What QGIS Version are you using?

![image](https://user-images.githubusercontent.com/28384354/165714132-c06b3606-22e4-4390-9bc1-28845d5f9387.png)

**Comment by gacarrillor** [comment]
Just in case you don't know it (or don't remember it), Model Baker allows users to set a custom order for form attributes.

You can do that passing a TOML file. Details at https://github.com/opengisch/QgisModelBaker/pull/440

**Comment by signedav** [comment]
Thanks for the reminder @gacarrillor that's something we should put into the documentation.

Still I think we should fix the order here.
